[paths]
app_path = "{{ cookiecutter.formal_name }}.app/Contents/Resources/app"
app_packages_path = "{{ cookiecutter.formal_name }}.app/Contents/Resources/app_packages"
support_path = "{{ cookiecutter.formal_name }}.app/Contents/Resources/support"
icon = "{{ cookiecutter.formal_name }}.app/Contents/Resources/{{ cookiecutter.app_name }}.icns"
{% for extension, doctype in cookiecutter.document_types.items() -%}
document_type_icon.{{ extension }} = "{{ cookiecutter.formal_name }}.app/Contents/Resources/{{ cookiecutter.app_name }}-{{ extension }}.icns"
{% endfor %}