name: Update binary
on:
  push:
    tags:
    - 'b*'

jobs:
  build-stubs:
    name: Build stub binaries
    runs-on: macos-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - name: Set build variables
      env:
        TAG_NAME: ${{ github.ref }}
      run: |
        export TAG=$(basename $TAG_NAME)
        echo "TAG=${TAG}"
        echo "TAG=${TAG}" >> $GITHUB_ENV
    - name: Checkout template
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version}}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install briefcase
    - name: Generate Xcode app template
      run: |
        # Generate the stub app
        cd stub
        briefcase create macOS Xcode
        briefcase build macOS Xcode
        # Since it's a generic stub binary, we can't provide any meaningful
        # signing credentials in the Xcode project. Remove the signature from
        # the stub binary.
        codesign --remove-signature ./macOS/Xcode/Stub/build/Release/Stub.app/Contents/MacOS/Stub
        mv macOS/Xcode/Stub/build/Release/Stub.app/Contents/MacOS/Stub Stub-${{ matrix.python-version }}
    - name: Upload Stub artefact
      uses: actions/upload-artifact@v3
      with:
        name: stubs
        path: stub/Stub-${{ matrix.python-version }}

  commit-stubs:
    name: Commit stub binaries
    needs: build-stubs
    runs-on: macos-latest
    steps:
    - name: Set build variables
      env:
        TAG_NAME: ${{ github.ref }}
      run: |
        export TAG=$(basename $TAG_NAME)
        echo "TAG=${TAG}"
        echo "TAG=${TAG}" >> $GITHUB_ENV
    - name: Checkout template
      uses: actions/checkout@v3
    - name: Download Stub artefacts
      uses: actions/download-artifact@v3
      with:
        name: stubs
        path: stub
    - name: Commit stubs
      run: |
        # Move the binary into it's final location
        mv stub/Stub-* "{{ cookiecutter.formal_name }}/{{ cookiecutter.formal_name }}.app/Contents/MacOS"
        git add "{{ cookiecutter.formal_name }}/{{ cookiecutter.formal_name }}.app/Contents/MacOS"
        git commit -m "AUTO: Update app binaries; build ${{ env.TAG }}"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
